<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-05-30T15:52:11 IST" name="Failed suite [Failed suite [Suite]]" finished-at="2022-05-30T15:52:36 IST" duration-ms="25029">
    <groups>
      <group name="sanity">
        <method signature="CreateOrganizationTest.createOrganizationTest()[pri:0, instance:com.OrganizationTest.CreateOrganizationTest@38ba6ce3]" name="createOrganizationTest" class="com.OrganizationTest.CreateOrganizationTest"/>
      </group> <!-- sanity -->
    </groups>
    <test started-at="2022-05-30T15:52:11 IST" name="Test(failed)(failed)" finished-at="2022-05-30T15:52:36 IST" duration-ms="25029">
      <class name="com.OrganizationTest.CreateOrganizationTest">
        <test-method is-config="true" signature="beforeSuite()[pri:0, instance:com.OrganizationTest.CreateOrganizationTest@38ba6ce3]" started-at="2022-05-30T15:52:10 IST" name="beforeSuite" finished-at="2022-05-30T15:52:11 IST" duration-ms="649" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method is-config="true" signature="beforeClass()[pri:0, instance:com.OrganizationTest.CreateOrganizationTest@38ba6ce3]" started-at="2022-05-30T15:52:11 IST" name="beforeClass" finished-at="2022-05-30T15:52:16 IST" duration-ms="5206" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:com.OrganizationTest.CreateOrganizationTest@38ba6ce3]" started-at="2022-05-30T15:52:16 IST" name="beforeMethod" finished-at="2022-05-30T15:52:20 IST" duration-ms="3783" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="createOrganizationTest()[pri:0, instance:com.OrganizationTest.CreateOrganizationTest@38ba6ce3]" started-at="2022-05-30T15:52:20 IST" name="createOrganizationTest" finished-at="2022-05-30T15:52:30 IST" duration-ms="9874" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at com.OrganizationTest.CreateOrganizationTest.createOrganizationTest(CreateOrganizationTest.java:25)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createOrganizationTest -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:com.OrganizationTest.CreateOrganizationTest@38ba6ce3]" started-at="2022-05-30T15:52:30 IST" name="afterMethod" finished-at="2022-05-30T15:52:36 IST" duration-ms="5715" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method is-config="true" signature="afterClass()[pri:0, instance:com.OrganizationTest.CreateOrganizationTest@38ba6ce3]" started-at="2022-05-30T15:52:36 IST" name="afterClass" finished-at="2022-05-30T15:52:36 IST" duration-ms="197" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
        <test-method is-config="true" signature="afterSuite()[pri:0, instance:com.OrganizationTest.CreateOrganizationTest@38ba6ce3]" started-at="2022-05-30T15:52:36 IST" name="afterSuite" finished-at="2022-05-30T15:52:36 IST" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- com.OrganizationTest.CreateOrganizationTest -->
    </test> <!-- Test(failed)(failed) -->
  </suite> <!-- Failed suite [Failed suite [Suite]] -->
</testng-results>
